- hosts: localhost
  tasks:
    - name: "to install httpd"
      package: 
         name: "httpd"
    - name: "Copying Web pages"
      copy: 
         dest: "/var/www/html/index.html"
         content: "TASK-12 Completed!!!!"
    - name: "Starting httpd servicre"
      service:
         name: "httpd"
         state: restarted
- hosts: mylb
  tasks:
    - name: "to install haproxy"
      package: 
         name: "haproxy"
    - name: "Configuring haproxy"
      template:
         dest: "/etc/haproxy/haproxy.cfg"
         src: "/root/haproxy.cfg"
    - name: "Starting haproxy Service"
      service:
         name: "haproxy"
         state: restarted