- hosts: localhost
  tasks:
  - name: "creating file for dvd"
    file: 
          state: directory
          path: "/dvd"

  - name: "Mountin DVD"
    mount:
          src: "/dev/cdrom"
          path: "/dvd"
          state: mounted
          fstype: "iso9660"

  - name: "Creating yum repos mydvd1"
    yum_repository:
          baseurl: "/dvd/AppStream"
          name: "mydvd1"
          description: "mdvd1"
          gpgcheck: no

  - name: "Creating yum repos mydvd2"
    yum_repository:
          baseurl: "/dvd/BaseOS"
          name: "mydvd2"
          description: "mydvd2"
          gpgcheck: no
          
  - name: "Creating yum repos docker"
    yum_repository:
          baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
          name: "docker"
          description: "docker-repo"
          gpgcheck: no

  - name: "Installing Dokcer-CE & Python36"
    package:
          name: "docker-ce-18.09.1-3.el7.x86_64,python36"

  - name: "Starting & Enabling service of docker:"
    service: 
          name: "docker"
          state: started
          enabled: yes
    
  - name: "Installing docker library"
    pip:
          name: "docker"

  - name: "Pulling httpd server from docker"
    docker_image:
          name: "httpd"
          source: pull

  - name: "Copying webpages"
    copy:
          dest: "/web/index.html"
          content: "ARTH TASK-10"

  - name: "launching docker container"
    community.general.docker_container:
          name: "webserver"
          image: "httpd"
          state: started
          exposed_ports:
                  - "80"
     
          volumes:
                  - /web:/usr/local/apache2/htdocs/

  - name: "Adding port no 80 to firewall"
    firewalld:
          port: 80/tcp
          state: enabled
          permanent: yes
          immediate: yes



