- hosts: localhost
  tasks:

  - name: "Creating yum repos docker"
    yum_repository:
          baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
          name: "docker1"
          description: "docker-repo"
          gpgcheck: no

  - name: "Installing Dokcer-CE & Python36"
    package:
          name: "docker-ce-18.09.1-3.el7.x86_64,python36"

  - name: "Starting & Enabling service of docker:"
    service: 
          name: "docker"
          state: started
          enabled: yes